In [1]:
# Create a 10x10 array with random values and find the minimum and maximum values.

In [25]:
import numpy as np
a = random.randint(1000,size=(10,10))
print("The orignal array: ")
print(a)
amin,amax=a.min(),a.max()
print("Minimum Value :",amin)
print()
print("Maximum Value: ",amax)

The orignal array: 
[[450 689 337  90 385 650 962 102 796 331]
 [947 755 581 114 902 820 663 793  68 867]
 [ 24 970 369 847 746 978  11  30  56 672]
 [534  90 106 160 212 334 165 513 519 156]
 [810 550 746 267 602 371 918  79 640  97]
 [265 951 123 947 494 841 529 567 220 674]
 [607  79 169 758 191 366 534 109 991 392]
 [260 184 733 617 476 674 301 214 578 437]
 [333 330 524 644 642 129 664 711 724 203]
 [503 702 571 954 298 497 804 781 340 357]]
Minimum Value : 11

Maximum Value:  991
